server:
  port: 9191 
  
spring:  application:    name: API-GATEWAY  
  cloud:    gateway:      routes:      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:        - Path=/users/** 
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/deaprtment/**  
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZaone: http://localhost:8761/eureka/
  instance:
    hostname: localhost         
      